#!/bin/bash

THIS_DIR=$(dirname $(readlink -f "$0"))
NICE_RUN='nice -18'

## Keyboard shortcuts
export SXHKD_SHELL=/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd -c "$THIS_DIR/sxhkdrc" & disown

## Xorg compositor
picom --config "$THIS_DIR/picom.conf" --daemon

## Wallpapers
$NICE_RUN "$THIS_DIR/tools/wallpaper.sh" & disown

## Status bar
killall -q polybar
$NICE_RUN polybar --config="$THIS_DIR/polybar.ini" --quiet main & disown

## Notifications
$NICE_RUN dunst -config "$THIS_DIR/dunstrc" & disown

## Clipboard manager
$NICE_RUN "$THIS_DIR/tools/clipboard.sh" daemon & disown

## Screen locker
$NICE_RUN "$THIS_DIR/tools/lockscr.sh" auto & disown

## Input method
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
fcitx5 -r -d --verbose default=0 > /dev/null 2>&1
