#! /bin/sh

#
# Environment setup
#

export _JAVA_AWT_WM_NONREPARENTING=1

xsetroot -cursor_name left_ptr

#
# Start programs
#

"$(dirname "$0")/autostart"

#
# bspwm: configuration
#

bspc monitor -d 壹 贰 叁 肆 伍 陆 柒 捌 玖 拾

bspc config border_width           2
bspc config window_gap             8
bspc config split_ratio            0.56
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true

#
# bspwm: rules
#

bspc rule -a 'KeePassXC' state=floating
bspc rule -a 'Minecraft Launcher' state=floating
bspc rule -a 'steam' state=floating
bspc rule -a 'Virt-manager:*:Virtual Machine Manager' state=floating
